- name: put {{ hadoop_distr_prefix }}/bin/portmap_start.sh
  template: src=portmap_start.sh dest={{ hadoop_distr_prefix }}/bin/portmap_start.sh
  when: "ansible_os_family == 'Elbrus'"

- name: chmod {{ hadoop_distr_prefix }}/bin/portmap_start.sh
  shell: chmod 0755 {{ hadoop_distr_prefix }}/bin/portmap_start.sh
  when: "ansible_os_family == 'Elbrus'"
